config/routes.rb
Rails.application.routes.draw do
  resources :publications
  devise_for :views
  devise_for :users

  post 'new_user_reaction',    to: 'reactions#new_user_reaction',   as:'new_user_reaction'


  resources :comments, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publication
  belongs_to :user
  has_many :reactions, dependent: :destroy
end

app/models/publication.rb
class Publication < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    has_many :users, through: :reactions


validates :kinds, acceptance:{
    accept: %w[ like dislike ].freeze
    }

def self.kinds
    %w[ like dislike ]
end

end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :publication, optional: true
  belongs_to :user
  belongs_to :comment, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reactions
  has_many :comments
  has_many :publications, through: :reactions
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected
        
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:mail, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:mail,:password])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @publication = Publication.find(params[:comment][:publication_id])
        @comment = Comment.new(comment_params)
        @comment.user = current_user
        respond_to do |format|
            if @comment.save
                format.html { redirect_to publication_path(@publication.id), notice: 'Has comentado con exito.' }
            else
                format.html { redirect_to publication_path(@publication.id), notice: 'Algo ha ocurrido.' }
            end
        end
    end

    private
    
    def comment_params
        params.require(:comment).permit(:contenido, :publication_id)
    end
           
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @comment = Comment.new
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

    def new_user_reaction
        @user = current_user
        @type = params[:reaction_type]
        @publication = Publication.find(params[:publication_id ]) if params[:publication_id]
        @comment = Comment.find(params[:comment_id]) if params[:comment_id]
        @kind = params[:kind]
        respond_to do |format|
            (@type == "comment") ? reaction_comment = Reaction.find_by(user_id: @user.id, comment_id: @comment.id) : reaction_publication = Reaction.find_by(user_id: @user.id, publication_id: @publication.id)
                if reaction_publication || reaction_comment
                    format.html { redirect_to publication_path(@publication), notice: 'Has reaccionado a la publicacion' }
                else
                    (@type == "publication") ? @reaction = Reaction.new(user_id: @user.id, publication_id: @publication.id, reaction_type: @type, kind: @kind): @reaction = Reaction.new(user_id: @user.id, comment_id: @comment.id, reaction_type: @type, kind: @kind)
                    if @reaction.save!
                        format.html {redirect_to publication_path(@publication), notice: 'La reaccion ha sucedido'}
                    else
                        format.html { redirect_to publication_path(@publication), notice: 'Algo salio mal'}
                    end
                end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
    <% if @comment.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este comentario no se pudo crear por las siguiente razones</h2>
            <ul>
                <% @comment.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

<%= f.hidden_field :publication_id, value: @publication.id %>
    <div class = 'field'>
        <%= f.label :"Crear Comentario", as: "Contenido" %>
        <%= f.text_field :contenido %>
    </div>
    <div class = 'actions'>
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/_publication_comment.html.erb
<div>
    <% @comments.each do |comment| %>
        <p>
            <%= comment.contenido %>
        </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioC4c</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/662e1443bf.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container back">
       <%= render "shared/navbar" %>
<% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% end %>
      <%= yield %>

    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
 
 
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Titulo:</strong>
    <%= publication.title %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= publication.description %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Ver más", @publication, class:"btn btn-dark btn-sm"%> 
  <%= link_to "Volver", publications_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/publications/index.html.erb
<div class="container titulo">
<h1>PubliCATciones <span><i class="fa-solid fa-cat me-2" ></i></span></h1>
</div>


<div id="publications">
  <% @publications.each do |publication| %>
     <div class="card">
        <div class="card-body border-star-2 border border-black rounded-2">
          <%= render publication %>
         <p>
          <%= link_to "Ver más", publication, class:"btn btn-dark btn-sm"%><span><i class="fa-solid fa-cat ms-auto"></i></span>
        </p>
        
        </div>
     </div>
              
    
  <% end %>

</div>

<%= link_to "Nueva Publicacion", new_publication_path, class:"btn btn-dark btn-sm" %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/publications/show.html.erb
<div class="container mt-5">
<div class="card">
  <div class="card-body border-star-2 border border-black rounded-2">
    <%= render @publication %>
    <div class="d-flex">
      <%= link_to "Editar", edit_publication_path(@publication), class:"btn btn-dark btn-sm me-2" %>
      <%= link_to "Volver", publications_path, class:"btn btn-dark btn-sm me-2" %>      
      <%= button_to "Eliminar esta publicación", @publication, method: :delete, class:"btn btn-dark btn-sm" %>
  </div>
  </div>
</div>

<div class="card">
  <div class="d-flex">
  <% if user_signed_in? %>
    <% Publication.kinds.each do |kind| %>
      <% if kind == 'like' %>
        <%= button_to "#{kind}", new_user_reaction_path(publication_id: @publication.id, reaction_type: "publication", kind: kind), method: :post, class:"btn btn-dark btn-sm" %><i class="fa-regular fa-thumbs-up" width="8px"></i>
      <% else %>
        <%= button_to "#{kind}", new_user_reaction_path(publication_id: @publication.id, reaction_type: "publication", kind: kind), method: :post, class:"btn btn-dark btn-sm" %><i class="fa-regular fa-thumbs-down" width="8px"></i>
      <% end %>    
    <% end %>
  <% end %>
</div>
 
  
  <div class="card">
    <div class="card-body border-star-2 border border-black rounded-2">
      <%= render 'comments/publication_comment' %>
    
      <%= render 'comments/form' %> 
    </div>
  </div>
  
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" data-bs-theme="dark">
  <div class="container-fluid texto">
    <i class="fa-solid fa-cat me-2" ></i>
    <%= link_to "Crazy 4 Cats", root_path, class:"nav-link active" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse me-auto" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Publicaciones", publications_path, class:"nav-link active" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
              Hola, <%= current_user.email%>   
            <% else %>
              Debes Registrate para conectarte
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= button_to "Cerrar Sesion", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% end %>
            <li><%= link_to "Iniciar Sesion", new_user_session_path, class:"dropdown-item" %></li>
            <li><%= link_to "Registro", new_user_registration_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>